language: android
dist: trusty

group: edge
jdk: oraclejdk8
branches:
  only:
  - master
  - develop
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
env:
  global:
    - ANDROID_API_LEVEL=27
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=27.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
android:
  components:
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
  sudo: false
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - intel-android-extra-license.+
  cache:
    directories:
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
before_install:
    - yes | sdkmanager
before_script:
  - ./code-check.sh
#after_success:
#  - ./bintray-upload.sh